le000:
	cd le000_base; pandoc --latex-engine=pdflatex -t beamer main.md -o ../le000_base.pdf
le001:
	cd le001_intro; pandoc --latex-engine=pdflatex -t beamer main.md -o ../le001_intro.pdf
le002:
	cd le002_programando; pandoc --latex-engine=pdflatex -t beamer main.md -o ../le002_programando.pdf
le003:
		cd le003_ejercicios; pandoc --latex-engine=pdflatex -t beamer main.md -o ../le003_ejercicios.pdf
le004:
		cd le004_io; pandoc --latex-engine=pdflatex -t beamer main.md -o ../le004_io.pdf
